### PR TITLE
Merge opencog/cogutil to singnet/cogutil

### PR DESCRIPTION
**Pull request by ngeiswei**
Contains PRs
- https://github.com/opencog/cogutil/pull/193
- https://github.com/opencog/cogutil/pull/194
- https://github.com/opencog/cogutil/pull/196
- https://github.com/opencog/cogutil/pull/197

### CODE REVIEW

**Comment by ngeiswei** [comment]
@vsbogd, github wants me to update the branch, can you make sense of that?

**Comment by vsbogd** [comment]
Hi @ngeiswei , did you started your `oc-to-sn` branch from `singnet/master` and merged opencog/master into it? Or you just forked `opencog/master` and raised PR from new branch? This repo has settings to restrict PR's which doesn't have latest branch state and I don't see my last commit in it.

**Comment by vsbogd** [comment]
Such restriction is necessary otherwise you build not what you will have after merge.

**Comment by ngeiswei** [comment]
Hi @vsbogd, I forked opencog/master and raised that PR from that new forked branch. Is it right?

> I don't see my last commit in it.

You mean your last commit to singnet/cogutil I suppose, right?

Thus I guess merge singnet/master to that branch is the correct procedure, right?

**Comment by vsbogd** [comment]
> Thus I guess merge singnet/master to that branch is the correct procedure, right?

Yes it should unblock merge.

Procedure I use is:
- create merge branch `oc-to-si` for example from `singnet/master`
- merge `opencog/master` to new branch `oc-to-si`
- raise PR from `oc-to-si` to `singnet/master`

Another way is to create `oc-to-si` from `opencog/master` and merge `singnet/master` into. It should work also, but I prefer first one as my understanding in that case merge should just move `singnet/master` HEAD to `oc-to-si` branch HEAD. Second procedure theoretically may add additional commit (but I am not very sure about it).

**Comment by ngeiswei** [comment]
I see. I'm gonna try your way (fork `singnet/master` instead of `opencog/master`) and compare the histories, thanks for the hint. Meanwhile I'm letting this PR open just in case.

**Comment by ngeiswei** [comment]
Yeah, your way is not bloating the git history as much. However I suspect, the history bloating might come back when we do sn->oc merge, but that's not for today (if ever). So I'm closing this PR and creating a new one singnet-based instead of opencog-based.

**Pull request closed without merging**
